name: Build Car Price API with Trained Model

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Print GitHub context
        run: |
            echo "Repository owner: ${{ github.repository_owner }}"
            echo "Actor: ${{ github.actor }}"
            echo "Repository: ${{ github.repository }}"
            echo "Owner LC: ${{ env.OWNER_LC }}"

      - name: Build MLflow image
        run: |
          docker build -t car-price-mlflow -f mlflow-server.Dockerfile .

      - name: Start MinIO
        run: |
          docker compose -f infra/minio/docker-compose.yml up -d
          sleep 10

      - name: Install DVC
        run: pip install dvc[s3]

      - name: Configure DVC remote
        run: |
          dvc remote add -d myremote s3://car-price-data
          dvc remote modify myremote endpointurl http://localhost:9000
          dvc remote modify myremote access_key_id minioadmin
          dvc remote modify myremote secret_access_key minioadmin

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install training dependencies
        run: pip install -r requirements_train.txt

      - name: Start temporary MLflow
        run: |
          docker run -d --name mlflow-temp --network host car-price-mlflow
          sleep 10

      - name: Pull data and train model
        env:
            MLFLOW_TRACKING_URI: http://localhost:5000
        run: |
          dvc pull
          python -m ml_model.train --data-path data/cars.csv

      - name: Stop MLflow
        run: |
          docker stop mlflow-temp || true
          docker rm mlflow-temp || true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.OWNER_LC }}/car-price-api:${{ github.sha }}, ghcr.io/${{ env.OWNER_LC }}/car-price-api:latest